[package]
name = "xlconv"
version = "0.3.0"
description = "Convert Excel to text."
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.24.0"
clap = { version = "4.5.1", features = ["derive"] }
