name: release

on:
  push:
    tags:
      - v*

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          components: rustfmt, clippy
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Release artifacts
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: target/release/xlconv{,.exe}
