name: release

on:
  push:
    tags:
      - v*

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Run cargo fmt
        run: cargo fmt
      - name: Run cargo clippy
        run: cargo clippy
  build:
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
          - aarch64-apple-darwin
          - aarch64-unknown-linux-gnu
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - name: build
        run: cargo build --release --all-features
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: target/release/
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
